export const resources = {
  en: {
    translation: {
      common: {
        loading: 'Loading...', saving: 'Saving...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', close: 'Close', add: 'Add', update: 'Update', apply: 'Apply', none: 'None', all: 'All', yes: 'Yes', no: 'No', optional: 'Optional', unknown: 'Unknown', error: 'Something went wrong', retry: 'Try again', amount: 'Amount', date: 'Date', comment: 'Comment', category: 'Category', title: 'Title', user: 'User', asset: 'Asset', operations: 'Operations', income: 'Income', expenses: 'Expenses', balance: 'Balance', transfer: 'Transfer', transfers: 'Transfers', settled: 'Settled', from: 'From', to: 'To', private: 'Private expense (not shared)', noResults: 'No results', preferenceSaved: 'Preference saved', preferenceFailed: 'Failed to save preference'
      },
      language: { label: 'Language', en: 'English', ru: 'Russian', de: 'German', he: 'Hebrew' },
      nav: { operations: 'Operations', statistics: 'Statistics', shared: 'Shared', preferences: 'Preferences', logout: 'Logout', userMenu: 'User menu' },
      auth: { tagline: 'Family Budget Management', signInGoogle: 'Sign in with Google' },
      dateRange: { previousMonth: 'Previous month', currentMonth: 'Current month', currentYear: 'Current year', allTime: 'All time', interval: 'History interval' },
      profile: {
        accounts: 'Accounts', assets: 'Assets', mutuals: 'Mutuals', categories: 'Categories', settings: 'Settings', simpleForm: 'Simple operation form', defaultMutual: 'Default mutual', defaultPurpose: 'Default purpose', defaultAsset: 'Default asset', defaultOperationType: 'Default operation type', noDefault: 'No default', addAccount: 'Add account', addAsset: 'Add asset', addMutual: 'Add mutual', addCategory: 'Add category', loadingProfile: 'Loading your profile...'
      },
      operations: {
        addOperation: 'Add operation', editing: 'Editing:', history: 'History', payment: 'Payment', lend: 'Lend', repay: 'Repay', dateTime: 'Date & time', purpose: 'Shared expense purpose', selectAsset: 'Select asset', selectDestination: 'Select destination asset...', targetAsset: 'Transfer to', exchangeRate: 'Exchange rate', recipientGets: 'Recipient gets:', loanRelationship: 'Loan relationship', titlePlaceholder: 'What was it for?', transferPlaceholder: 'Transfer description', categoryPlaceholder: 'e.g. Food, Transport', commentPlaceholder: 'Optional notes...', addPayment: 'Add payment', addIncome: 'Add income', addTransfer: 'Add transfer', addLend: 'Record loan', addRepay: 'Record repayment', updateOperation: 'Update operation', deleteOperation: 'Delete operation', chooseHistory: 'Choose from history', previousOperations: 'Previous operations', noMatching: 'No matching operations', commentItems: 'Comment items', addCommentItem: 'Add a new comment item', noCommentItems: 'No saved comment items', additionalDetails: 'Additional details', noOperations: 'No operations', noOperationsFilter: 'No operations match the current filter.', loadingHistory: 'Loading history...', clickToEdit: 'Click a row to edit or delete', mutualOn: 'Showing mutual participant operations', mutualOff: 'Show mutual participant operations', externalAsset: 'External mutual asset', noAssets: 'No assets found', noAssetsHelp: 'You need at least one asset to record operations.'
      },
      statistics: {
        title: 'Statistics', calculating: 'Calculating statistics...', noAssets: 'No visible assets', noAssetsHelp: 'Add an asset to start building statistics.', periodOverview: 'Period overview', netCashFlow: 'Net cash flow', loanPosition: 'Loan position', owedToYou: 'Owed to you', youOwe: 'You owe', periodDetails: 'Period details', periodDetailsHint: 'Useful context behind the totals', averageIncome: 'Average daily income', averageSpending: 'Average daily spending', averageNet: 'Average daily net', largestExpense: 'Largest expense', visibleAssets: 'Visible assets', dailyCashFlow: 'Daily cash flow', monthlyCashFlow: 'Monthly cash flow', cashFlowHint: 'Net income after expenses', positive: 'Positive', negative: 'Negative', noPeriodOperations: 'No operations in this period.', categories: 'Categories', hierarchyHint: 'Income and expenses in one hierarchy', measurements: 'Measurements', measurementsHint: 'Category-defined quantities, prices, and meter readings', latestReading: 'Latest reading', carCosts: 'Car costs', totalCost: 'Total cost', costPerDay: 'Cost / day', fuelCost: 'Fuel cost', averagePerLiter: 'Average / liter', trackedDistance: 'Tracked distance', fuelConsumption: 'Fuel consumption', fuelPerKm: 'Fuel / km', dataCoverage: 'Fuel data coverage', bankReconciliation: 'Bank reconciliation'
      },
      mutuals: {
        sharedExpenses: 'Shared expenses', loanLedger: 'Loan ledger', trackShared: 'Track and settle mutual expenses', trackLoans: 'Track advances, repayments, and current debt', mutualGroup: 'Mutual group', purpose: 'Purpose', allPurposes: 'All purposes', noGroups: 'No shared accounts', noGroupsHelp: 'You are not part of any mutual expense sharing group.', loadingGroups: 'Loading mutuals...', filterDate: 'Filter by date', settlementSummary: 'Settlement summary', totalShared: 'Total shared expenses', expected: 'Expected', actuallyPaid: 'Actually paid', fromAsset: 'From asset', toAsset: 'To asset', settlementDate: 'Settlement date', applySettlement: 'Apply settlement', noSettlement: 'No settlement is currently needed.', settlementHistory: 'Settlement history', noSettlements: 'No settlements have been applied yet.', currentDebt: 'Current debt', lender: 'Lender', borrower: 'Borrower', loanAdvance: 'Loan advance', repayment: 'Repayment'
      },
      reconciliation: { title: 'Bank reconciliation', selectAsset: 'Asset to reconcile', importExcel: 'Import Excel', loadingAssets: 'Loading assets...', chooseFile: 'Choose a Bank Hapoalim Excel statement', privacy: 'The file stays in this browser. No bank data is written to Firestore.', bankTransaction: 'Bank transaction', status: 'Status', appOperation: 'MyMoney operation', noDirect: 'No direct operation' }
    }
  },
  ru: {
    translation: {
      common: {
        loading: 'Загрузка...', saving: 'Сохранение...', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить', close: 'Закрыть', add: 'Добавить', update: 'Обновить', apply: 'Применить', none: 'Нет', all: 'Все', yes: 'Да', no: 'Нет', optional: 'Необязательно', unknown: 'Неизвестно', error: 'Произошла ошибка', retry: 'Повторить', amount: 'Сумма', date: 'Дата', comment: 'Комментарий', category: 'Категория', title: 'Название', user: 'Пользователь', asset: 'Актив', operations: 'Операции', income: 'Доходы', expenses: 'Расходы', balance: 'Баланс', transfer: 'Перевод', transfers: 'Переводы', settled: 'Погашено', from: 'С', to: 'По', private: 'Личная операция (не общая)', noResults: 'Нет результатов', preferenceSaved: 'Настройка сохранена', preferenceFailed: 'Не удалось сохранить настройку'
      },
      language: { label: 'Язык', en: 'Английский', ru: 'Русский', de: 'Немецкий', he: 'Иврит' },
      nav: { operations: 'Операции', statistics: 'Статистика', shared: 'Общие', preferences: 'Настройки', logout: 'Выйти', userMenu: 'Меню пользователя' },
      auth: { tagline: 'Управление семейным бюджетом', signInGoogle: 'Войти через Google' },
      dateRange: { previousMonth: 'Предыдущий месяц', currentMonth: 'Текущий месяц', currentYear: 'Текущий год', allTime: 'Всё время', interval: 'Период истории' },
      profile: { accounts: 'Счета', assets: 'Активы', mutuals: 'Общие группы', categories: 'Категории', settings: 'Настройки', simpleForm: 'Простая форма операции', defaultMutual: 'Общая группа по умолчанию', defaultPurpose: 'Назначение по умолчанию', defaultAsset: 'Актив по умолчанию', defaultOperationType: 'Тип операции по умолчанию', noDefault: 'Не задано', addAccount: 'Добавить счёт', addAsset: 'Добавить актив', addMutual: 'Добавить общую группу', addCategory: 'Добавить категорию', loadingProfile: 'Загрузка профиля...' },
      operations: { addOperation: 'Добавить операцию', editing: 'Изменение:', history: 'История', payment: 'Расход', lend: 'Одолжить', repay: 'Вернуть', dateTime: 'Дата и время', purpose: 'Назначение общего расхода', selectAsset: 'Выберите актив', selectDestination: 'Выберите актив назначения...', targetAsset: 'Перевести на', exchangeRate: 'Курс обмена', recipientGets: 'Получатель получит:', loanRelationship: 'Долговая группа', titlePlaceholder: 'На что потрачено?', transferPlaceholder: 'Описание перевода', categoryPlaceholder: 'Например, еда, транспорт', commentPlaceholder: 'Необязательные заметки...', addPayment: 'Добавить расход', addIncome: 'Добавить доход', addTransfer: 'Добавить перевод', addLend: 'Записать заём', addRepay: 'Записать возврат', updateOperation: 'Обновить операцию', deleteOperation: 'Удалить операцию', chooseHistory: 'Выбрать из истории', previousOperations: 'Предыдущие операции', noMatching: 'Похожих операций нет', commentItems: 'Пункты комментария', addCommentItem: 'Добавить новый пункт', noCommentItems: 'Сохранённых пунктов нет', additionalDetails: 'Дополнительные данные', noOperations: 'Нет операций', noOperationsFilter: 'Нет операций, соответствующих фильтру.', loadingHistory: 'Загрузка истории...', clickToEdit: 'Нажмите строку для изменения или удаления', mutualOn: 'Показаны операции других участников', mutualOff: 'Показать операции других участников', externalAsset: 'Актив другого участника', noAssets: 'Активы не найдены', noAssetsHelp: 'Для записи операций нужен хотя бы один актив.' },
      statistics: { title: 'Статистика', calculating: 'Расчёт статистики...', noAssets: 'Нет видимых активов', noAssetsHelp: 'Добавьте актив, чтобы построить статистику.', periodOverview: 'Итоги периода', netCashFlow: 'Чистый денежный поток', loanPosition: 'Долговая позиция', owedToYou: 'Должны вам', youOwe: 'Вы должны', periodDetails: 'Данные периода', periodDetailsHint: 'Полезные показатели за выбранный период', averageIncome: 'Средний доход в день', averageSpending: 'Средний расход в день', averageNet: 'Среднее нетто в день', largestExpense: 'Крупнейший расход', visibleAssets: 'Видимые активы', dailyCashFlow: 'Денежный поток по дням', monthlyCashFlow: 'Денежный поток по месяцам', cashFlowHint: 'Чистый доход после расходов', positive: 'Плюс', negative: 'Минус', noPeriodOperations: 'За этот период операций нет.', categories: 'Категории', hierarchyHint: 'Доходы и расходы в одной иерархии', measurements: 'Измерения', measurementsHint: 'Количество, цены и показания, заданные в категориях', latestReading: 'Последнее показание', carCosts: 'Расходы на автомобиль', totalCost: 'Общая стоимость', costPerDay: 'Стоимость в день', fuelCost: 'Стоимость топлива', averagePerLiter: 'Средняя цена литра', trackedDistance: 'Учтённый пробег', fuelConsumption: 'Расход топлива', fuelPerKm: 'Топливо на км', dataCoverage: 'Полнота данных о топливе', bankReconciliation: 'Сверка с банком' },
      mutuals: { sharedExpenses: 'Общие расходы', loanLedger: 'Долговая книга', trackShared: 'Учёт и расчёт общих расходов', trackLoans: 'Займы, возвраты и текущий долг', mutualGroup: 'Общая группа', purpose: 'Назначение', allPurposes: 'Все назначения', noGroups: 'Нет общих групп', noGroupsHelp: 'Вы не состоите ни в одной группе общих расходов.', loadingGroups: 'Загрузка групп...', filterDate: 'Фильтр по дате', settlementSummary: 'Итог взаиморасчётов', totalShared: 'Всего общих расходов', expected: 'Ожидалось', actuallyPaid: 'Фактически оплачено', fromAsset: 'Из актива', toAsset: 'В актив', settlementDate: 'Дата расчёта', applySettlement: 'Применить расчёт', noSettlement: 'Сейчас взаиморасчёт не требуется.', settlementHistory: 'История взаиморасчётов', noSettlements: 'Взаиморасчёты ещё не применялись.', currentDebt: 'Текущий долг', lender: 'Кредитор', borrower: 'Заёмщик', loanAdvance: 'Выдача займа', repayment: 'Возврат долга' },
      reconciliation: { title: 'Сверка с банком', selectAsset: 'Актив для сверки', importExcel: 'Импорт Excel', loadingAssets: 'Загрузка активов...', chooseFile: 'Выберите выписку Bank Hapoalim в Excel', privacy: 'Файл остаётся в браузере. Банковские данные не записываются в Firestore.', bankTransaction: 'Операция банка', status: 'Статус', appOperation: 'Операция MyMoney', noDirect: 'Прямого соответствия нет' }
    }
  },
  de: {
    translation: {
      common: { loading: 'Wird geladen...', saving: 'Wird gespeichert...', save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', close: 'Schließen', add: 'Hinzufügen', update: 'Aktualisieren', apply: 'Anwenden', none: 'Keine', all: 'Alle', yes: 'Ja', no: 'Nein', optional: 'Optional', unknown: 'Unbekannt', error: 'Ein Fehler ist aufgetreten', retry: 'Erneut versuchen', amount: 'Betrag', date: 'Datum', comment: 'Kommentar', category: 'Kategorie', title: 'Titel', user: 'Benutzer', asset: 'Vermögenswert', operations: 'Buchungen', income: 'Einnahmen', expenses: 'Ausgaben', balance: 'Saldo', transfer: 'Umbuchung', transfers: 'Umbuchungen', settled: 'Ausgeglichen', from: 'Von', to: 'Bis', private: 'Private Buchung (nicht geteilt)', noResults: 'Keine Ergebnisse', preferenceSaved: 'Einstellung gespeichert', preferenceFailed: 'Einstellung konnte nicht gespeichert werden' },
      language: { label: 'Sprache', en: 'Englisch', ru: 'Russisch', de: 'Deutsch', he: 'Hebräisch' },
      nav: { operations: 'Buchungen', statistics: 'Statistik', shared: 'Gemeinsam', preferences: 'Einstellungen', logout: 'Abmelden', userMenu: 'Benutzermenü' },
      auth: { tagline: 'Verwaltung des Familienbudgets', signInGoogle: 'Mit Google anmelden' },
      dateRange: { previousMonth: 'Vorheriger Monat', currentMonth: 'Aktueller Monat', currentYear: 'Aktuelles Jahr', allTime: 'Gesamter Zeitraum', interval: 'Zeitraum der Historie' },
      profile: { accounts: 'Konten', assets: 'Vermögenswerte', mutuals: 'Gemeinsame Gruppen', categories: 'Kategorien', settings: 'Einstellungen', simpleForm: 'Einfaches Buchungsformular', defaultMutual: 'Standardgruppe', defaultPurpose: 'Standardzweck', defaultAsset: 'Standardvermögenswert', defaultOperationType: 'Standardbuchungsart', noDefault: 'Nicht festgelegt', addAccount: 'Konto hinzufügen', addAsset: 'Vermögenswert hinzufügen', addMutual: 'Gemeinsame Gruppe hinzufügen', addCategory: 'Kategorie hinzufügen', loadingProfile: 'Profil wird geladen...' },
      operations: { addOperation: 'Buchung hinzufügen', editing: 'Bearbeiten:', history: 'Verlauf', payment: 'Ausgabe', lend: 'Verleihen', repay: 'Zurückzahlen', dateTime: 'Datum und Uhrzeit', purpose: 'Zweck der gemeinsamen Ausgabe', selectAsset: 'Vermögenswert auswählen', selectDestination: 'Ziel auswählen...', targetAsset: 'Umbuchen nach', exchangeRate: 'Wechselkurs', recipientGets: 'Empfänger erhält:', loanRelationship: 'Darlehensgruppe', titlePlaceholder: 'Wofür war es?', transferPlaceholder: 'Beschreibung der Umbuchung', categoryPlaceholder: 'z. B. Essen, Transport', commentPlaceholder: 'Optionale Notizen...', addPayment: 'Ausgabe hinzufügen', addIncome: 'Einnahme hinzufügen', addTransfer: 'Umbuchung hinzufügen', addLend: 'Darlehen erfassen', addRepay: 'Rückzahlung erfassen', updateOperation: 'Buchung aktualisieren', deleteOperation: 'Buchung löschen', chooseHistory: 'Aus Verlauf auswählen', previousOperations: 'Frühere Buchungen', noMatching: 'Keine passenden Buchungen', commentItems: 'Kommentarbausteine', addCommentItem: 'Neuen Baustein hinzufügen', noCommentItems: 'Keine gespeicherten Bausteine', additionalDetails: 'Zusätzliche Angaben', noOperations: 'Keine Buchungen', noOperationsFilter: 'Keine Buchungen entsprechen dem Filter.', loadingHistory: 'Verlauf wird geladen...', clickToEdit: 'Zeile anklicken, um sie zu bearbeiten oder zu löschen', mutualOn: 'Buchungen anderer Teilnehmer werden angezeigt', mutualOff: 'Buchungen anderer Teilnehmer anzeigen', externalAsset: 'Vermögenswert eines anderen Teilnehmers', noAssets: 'Keine Vermögenswerte gefunden', noAssetsHelp: 'Zum Erfassen von Buchungen ist mindestens ein Vermögenswert erforderlich.' },
      statistics: { title: 'Statistik', calculating: 'Statistik wird berechnet...', noAssets: 'Keine sichtbaren Vermögenswerte', noAssetsHelp: 'Fügen Sie einen Vermögenswert hinzu, um Statistiken zu erstellen.', periodOverview: 'Zeitraumübersicht', netCashFlow: 'Netto-Cashflow', loanPosition: 'Darlehensposition', owedToYou: 'Forderungen', youOwe: 'Verbindlichkeiten', periodDetails: 'Zeitraumdetails', periodDetailsHint: 'Nützlicher Kontext zu den Summen', averageIncome: 'Durchschnittliche Tageseinnahmen', averageSpending: 'Durchschnittliche Tagesausgaben', averageNet: 'Durchschnittlicher Tagessaldo', largestExpense: 'Größte Ausgabe', visibleAssets: 'Sichtbare Vermögenswerte', dailyCashFlow: 'Täglicher Cashflow', monthlyCashFlow: 'Monatlicher Cashflow', cashFlowHint: 'Nettoeinnahmen nach Ausgaben', positive: 'Positiv', negative: 'Negativ', noPeriodOperations: 'Keine Buchungen in diesem Zeitraum.', categories: 'Kategorien', hierarchyHint: 'Einnahmen und Ausgaben in einer Hierarchie', measurements: 'Messwerte', measurementsHint: 'Von Kategorien definierte Mengen, Preise und Zählerstände', latestReading: 'Letzter Messwert', carCosts: 'Fahrzeugkosten', totalCost: 'Gesamtkosten', costPerDay: 'Kosten pro Tag', fuelCost: 'Kraftstoffkosten', averagePerLiter: 'Durchschnitt pro Liter', trackedDistance: 'Erfasste Strecke', fuelConsumption: 'Kraftstoffverbrauch', fuelPerKm: 'Kraftstoff pro km', dataCoverage: 'Abdeckung der Kraftstoffdaten', bankReconciliation: 'Bankabgleich' },
      mutuals: { sharedExpenses: 'Gemeinsame Ausgaben', loanLedger: 'Darlehensbuch', trackShared: 'Gemeinsame Ausgaben erfassen und ausgleichen', trackLoans: 'Darlehen, Rückzahlungen und aktuelle Schulden erfassen', mutualGroup: 'Gemeinsame Gruppe', purpose: 'Zweck', allPurposes: 'Alle Zwecke', noGroups: 'Keine gemeinsamen Gruppen', noGroupsHelp: 'Sie gehören keiner Gruppe für gemeinsame Ausgaben an.', loadingGroups: 'Gruppen werden geladen...', filterDate: 'Nach Datum filtern', settlementSummary: 'Ausgleichsübersicht', totalShared: 'Gemeinsame Ausgaben gesamt', expected: 'Erwartet', actuallyPaid: 'Tatsächlich bezahlt', fromAsset: 'Von Vermögenswert', toAsset: 'Zu Vermögenswert', settlementDate: 'Ausgleichsdatum', applySettlement: 'Ausgleich anwenden', noSettlement: 'Derzeit ist kein Ausgleich erforderlich.', settlementHistory: 'Ausgleichsverlauf', noSettlements: 'Es wurden noch keine Ausgleiche angewendet.', currentDebt: 'Aktuelle Schuld', lender: 'Darlehensgeber', borrower: 'Darlehensnehmer', loanAdvance: 'Darlehensauszahlung', repayment: 'Rückzahlung' },
      reconciliation: { title: 'Bankabgleich', selectAsset: 'Abzugleichender Vermögenswert', importExcel: 'Excel importieren', loadingAssets: 'Vermögenswerte werden geladen...', chooseFile: 'Bank-Hapoalim-Auszug als Excel auswählen', privacy: 'Die Datei bleibt in diesem Browser. Es werden keine Bankdaten in Firestore gespeichert.', bankTransaction: 'Banktransaktion', status: 'Status', appOperation: 'MyMoney-Buchung', noDirect: 'Keine direkte Buchung' }
    }
  },
  he: {
    translation: {
      common: { loading: 'טוען...', saving: 'שומר...', save: 'שמירה', cancel: 'ביטול', delete: 'מחיקה', edit: 'עריכה', close: 'סגירה', add: 'הוספה', update: 'עדכון', apply: 'החלה', none: 'ללא', all: 'הכול', yes: 'כן', no: 'לא', optional: 'אופציונלי', unknown: 'לא ידוע', error: 'אירעה שגיאה', retry: 'נסה שוב', amount: 'סכום', date: 'תאריך', comment: 'הערה', category: 'קטגוריה', title: 'כותרת', user: 'משתמש', asset: 'נכס', operations: 'פעולות', income: 'הכנסות', expenses: 'הוצאות', balance: 'יתרה', transfer: 'העברה', transfers: 'העברות', settled: 'נסגר', from: 'מ־', to: 'עד', private: 'פעולה פרטית (לא משותפת)', noResults: 'אין תוצאות', preferenceSaved: 'ההעדפה נשמרה', preferenceFailed: 'שמירת ההעדפה נכשלה' },
      language: { label: 'שפה', en: 'אנגלית', ru: 'רוסית', de: 'גרמנית', he: 'עברית' },
      nav: { operations: 'פעולות', statistics: 'סטטיסטיקה', shared: 'משותף', preferences: 'הגדרות', logout: 'התנתקות', userMenu: 'תפריט משתמש' },
      auth: { tagline: 'ניהול תקציב משפחתי', signInGoogle: 'כניסה באמצעות Google' },
      dateRange: { previousMonth: 'החודש הקודם', currentMonth: 'החודש הנוכחי', currentYear: 'השנה הנוכחית', allTime: 'כל התקופה', interval: 'טווח היסטוריה' },
      profile: { accounts: 'חשבונות', assets: 'נכסים', mutuals: 'קבוצות משותפות', categories: 'קטגוריות', settings: 'הגדרות', simpleForm: 'טופס פעולה פשוט', defaultMutual: 'קבוצה משותפת ברירת מחדל', defaultPurpose: 'מטרה ברירת מחדל', defaultAsset: 'נכס ברירת מחדל', defaultOperationType: 'סוג פעולה ברירת מחדל', noDefault: 'לא הוגדר', addAccount: 'הוספת חשבון', addAsset: 'הוספת נכס', addMutual: 'הוספת קבוצה משותפת', addCategory: 'הוספת קטגוריה', loadingProfile: 'טוען פרופיל...' },
      operations: { addOperation: 'הוספת פעולה', editing: 'עריכה:', history: 'היסטוריה', payment: 'הוצאה', lend: 'הלוואה', repay: 'החזר', dateTime: 'תאריך ושעה', purpose: 'מטרת הוצאה משותפת', selectAsset: 'בחירת נכס', selectDestination: 'בחירת נכס יעד...', targetAsset: 'העברה אל', exchangeRate: 'שער חליפין', recipientGets: 'המקבל יקבל:', loanRelationship: 'קבוצת הלוואה', titlePlaceholder: 'עבור מה?', transferPlaceholder: 'תיאור ההעברה', categoryPlaceholder: 'למשל מזון, תחבורה', commentPlaceholder: 'הערות אופציונליות...', addPayment: 'הוספת הוצאה', addIncome: 'הוספת הכנסה', addTransfer: 'הוספת העברה', addLend: 'רישום הלוואה', addRepay: 'רישום החזר', updateOperation: 'עדכון פעולה', deleteOperation: 'מחיקת פעולה', chooseHistory: 'בחירה מההיסטוריה', previousOperations: 'פעולות קודמות', noMatching: 'אין פעולות תואמות', commentItems: 'פריטי הערה', addCommentItem: 'הוספת פריט חדש', noCommentItems: 'אין פריטים שמורים', additionalDetails: 'פרטים נוספים', noOperations: 'אין פעולות', noOperationsFilter: 'אין פעולות התואמות למסנן.', loadingHistory: 'טוען היסטוריה...', clickToEdit: 'לחצו על שורה לעריכה או למחיקה', mutualOn: 'מוצגות פעולות של משתתפים אחרים', mutualOff: 'הצגת פעולות של משתתפים אחרים', externalAsset: 'נכס של משתתף אחר', noAssets: 'לא נמצאו נכסים', noAssetsHelp: 'נדרש לפחות נכס אחד כדי לרשום פעולות.' },
      statistics: { title: 'סטטיסטיקה', calculating: 'מחשב סטטיסטיקה...', noAssets: 'אין נכסים גלויים', noAssetsHelp: 'הוסיפו נכס כדי להתחיל לבנות סטטיסטיקה.', periodOverview: 'סקירת התקופה', netCashFlow: 'תזרים מזומנים נטו', loanPosition: 'מצב הלוואות', owedToYou: 'חייבים לך', youOwe: 'אתה חייב', periodDetails: 'פרטי התקופה', periodDetailsHint: 'מידע שימושי מאחורי הסיכומים', averageIncome: 'הכנסה יומית ממוצעת', averageSpending: 'הוצאה יומית ממוצעת', averageNet: 'נטו יומי ממוצע', largestExpense: 'ההוצאה הגדולה ביותר', visibleAssets: 'נכסים גלויים', dailyCashFlow: 'תזרים יומי', monthlyCashFlow: 'תזרים חודשי', cashFlowHint: 'הכנסה נטו לאחר הוצאות', positive: 'חיובי', negative: 'שלילי', noPeriodOperations: 'אין פעולות בתקופה זו.', categories: 'קטגוריות', hierarchyHint: 'הכנסות והוצאות בהיררכיה אחת', measurements: 'מדידות', measurementsHint: 'כמויות, מחירים וקריאות מונה שהוגדרו בקטגוריות', latestReading: 'קריאה אחרונה', carCosts: 'הוצאות רכב', totalCost: 'עלות כוללת', costPerDay: 'עלות ליום', fuelCost: 'עלות דלק', averagePerLiter: 'ממוצע לליטר', trackedDistance: 'מרחק מתועד', fuelConsumption: 'צריכת דלק', fuelPerKm: 'דלק לק״מ', dataCoverage: 'כיסוי נתוני דלק', bankReconciliation: 'התאמת בנק' },
      mutuals: { sharedExpenses: 'הוצאות משותפות', loanLedger: 'פנקס הלוואות', trackShared: 'מעקב וסגירת הוצאות משותפות', trackLoans: 'מעקב אחר הלוואות, החזרים וחוב נוכחי', mutualGroup: 'קבוצה משותפת', purpose: 'מטרה', allPurposes: 'כל המטרות', noGroups: 'אין קבוצות משותפות', noGroupsHelp: 'אינך חבר בקבוצת הוצאות משותפות.', loadingGroups: 'טוען קבוצות...', filterDate: 'סינון לפי תאריך', settlementSummary: 'סיכום התחשבנות', totalShared: 'סך ההוצאות המשותפות', expected: 'צפוי', actuallyPaid: 'שולם בפועל', fromAsset: 'מנכס', toAsset: 'לנכס', settlementDate: 'תאריך התחשבנות', applySettlement: 'החלת התחשבנות', noSettlement: 'כרגע אין צורך בהתחשבנות.', settlementHistory: 'היסטוריית התחשבנויות', noSettlements: 'טרם הוחלו התחשבנויות.', currentDebt: 'חוב נוכחי', lender: 'מלווה', borrower: 'לווה', loanAdvance: 'מתן הלוואה', repayment: 'החזר הלוואה' },
      reconciliation: { title: 'התאמת בנק', selectAsset: 'נכס להתאמה', importExcel: 'ייבוא Excel', loadingAssets: 'טוען נכסים...', chooseFile: 'בחרו דוח Excel של בנק הפועלים', privacy: 'הקובץ נשאר בדפדפן. נתוני הבנק אינם נכתבים ל-Firestore.', bankTransaction: 'פעולת בנק', status: 'סטטוס', appOperation: 'פעולת MyMoney', noDirect: 'אין פעולה ישירה' }
    }
  }
} as const
